api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "buy-2-get-free"
type = "function"
uid = "4ab7348d-ced7-2c54-ce2c-04254b0b1830d5ef1dfa"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/discount/:functionId/new"
  details = "/app/discount/:functionId/:id"
